version: '3'

services:
  nginx:
    image: nginx:1.17
    ports:
      - 8080:80
    volumes:
      - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php

  php:
    #image: php:7.4-fpm
    build: ./build/docker/php
    volumes:
      - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}

  mariadb:
    image: mariadb:10.3
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ${DB_PATH_HOST}:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: qwerty

  composer:
    image: composer:1.10
    volumes:
      - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
    working_dir: ${APP_PATH_CONTAINER}
    command: composer install